CREATE TABLE IF NOT EXISTS `activity` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` TEXT(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS `activity_type` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` TEXT(10) NOT NULL,
  `activity` INTEGER,
  FOREIGN KEY (`activity`) REFERENCES `activity`(`id`)
);
